/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 portifolio.glb 
*/

import { useLayoutEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../src/components/objects3D/portifolio.glb')
  const { actions } = useAnimations(animations, group)

  useLayoutEffect(() => {
    actions.VazioAction.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Vazio" position={[0.183, -0.696, 2.641]} scale={[0.7, 0.7, 0.173]}>
          <mesh name="Cilindro001" geometry={nodes.Cilindro001.geometry} material={materials.MatRodas} position={[-0.261, 0.387, -1.177]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.083, 0.243, 0.083]} />
        </group>
        <mesh name="Fundo" geometry={nodes.Fundo.geometry} material={materials.Mat_Fundo} position={[-0.114, 0.478, 0]} scale={[0.055, 0.801, 2.611]} />
        <mesh name="Cilindro" geometry={nodes.Cilindro.geometry} material={materials.Mat_Fundo} position={[0, -0.426, 0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.058, 2.481, 0.058]} />
        <mesh name="Relicario" geometry={nodes.Relicario.geometry} material={materials.Mat_Relicario} position={[0, 0.596, 2.038]} rotation={[0, 0, -Math.PI / 2]} scale={0.434} />
        <mesh name="Texto" geometry={nodes.Texto.geometry} material={materials.Mat_letras} position={[0, 0.715, 1.43]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.497} />
        <mesh name="Texto001" geometry={nodes.Texto001.geometry} material={materials.Mat_letras} position={[0, 0.405, 1.328]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.146} />
        <mesh name="Texto002" geometry={nodes.Texto002.geometry} material={materials.Mat_letras} position={[0, -0.142, 2.458]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.135} />
      </group>
    </group>
  )
}

useGLTF.preload('../src/components/objects3D/portifolio.glb')
